[build]
  command = "./build.sh"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Direct APK download redirects
[[redirects]]
  from = "/download/mdm-dpc-app.apk"
  to = "/public/downloads/mdm-dpc-app.apk"
  status = 200

[[redirects]]
  from = "/download/app.apk"
  to = "/public/downloads/mdm-dpc-app.apk"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
