[build]
  command = "./build.sh"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Global headers for APK files
[[headers]]
  for = "*.apk"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Direct APK file serving (no redirects)
[[headers]]
  for = "/public/downloads/mdm-dpc-app.apk"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=\"mdm-dpc-app.apk\""
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Alternative direct URLs for convenience
[[headers]]
  for = "/downloads/mdm-dpc-app.apk"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment; filename=\"mdm-dpc-app.apk\""
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
